bot:
  prefix: "!"

guilds:
  - id: 486184376544002073
    name: "fi_muni"

    NEEDED_REACTIONS: 10
    STARBOARD_REACT_LIMIT: 10
    DEBUG: False

    channels:
      verification:         621365818034356224
      about_you:            621365826372632606
      subject_registration: 628684083345489950
      starboard:            761552082159271936

    logs:
      errors:               609413180137144331
      mute:                 null
      other:                null

    roles:
      muted:                627901278365810698
      verified:             621304939502632960
      moderator:            null
      admin:                504237720965480450
      show_all:             628684833039712266

  - id: 573528762843660299
    name: "fi test"

    NEEDED_REACTIONS: 1
    STARBOARD_REACT_LIMIT: 1
    DEBUG: False

    channels:
      verification:         731525269214724116
      about_you:            760211019405590540
      subject_registration: 758267743119212576
      starboard:            751062312781217792

    logs:
      errors:               731435433564569632
      mute:                 731435469472006156
      other:                731435447787716680

    roles:
      muted:                null
      verified:             740961005961609328
      moderator:            627249759694094366
      admin:                573595915302993920
      show_all:             760093273871613993

emoji:
  Verification: 617745093889359872

colors:
  MUNI_YELLOW: 0xEACD59